---
- name: 
  hosts: Node_01
  become: true
  tasks:
  - name:
    lineinfile:
      path: "/tmp/logline.log"
      line: 'Hello World111111'
      regexp: "^Hello World ([2-4])$"
      state: present
      create: true