---
- name: 
  hosts: Node_01
  become: true
  tasks:
  - name: "alterar arquivo /etc/ssh/sshd_config"
    lineinfile: 
      path: "/tmp/logline.log"
      line: | 
        # Hello World 1
        # Hello World 2
        # Hello World 3
        # Hello World 4
        # Hello World 5
        # Hello World 6
        # Hello World 7
      create: true
      

