--- 
- name: "Loop dicionario"
  hosts: Node_01
  vars:
    HIBSA1:
        ip: 10.10.10.10
        fabricante: Ericsson
        tipo: vHSS
        versao_sw: 1.31
        nome_do_elemento: hibsa1

  tasks:
  - name: "Printout dicionario"
    debug:
       msg:
        - "{{ item.key }}  {{ item.value }}"
    loop: "{{ HIBSA1 | dict2items }}"     

