---
- name: "Estrutura de decisao"
  hosts: Node_01
  gather_facts: true
  tasks:
  - name: "Imprime gather_facts"
    debug:
      msg: 
       - "{{ ansible_facts.os_family }}"
       - "{{ ansible_facts.machine }} "
    when: 
     - ansible_facts['os_family'] == "Debian"    
     - ansible_facts['machine' ] == "x86_64" 

 