---
- name: "Estrutura de decisao"
  hosts: Node_01
  gather_facts: false
  vars:
    flag: 1
        
  vars_prompt:
  - name: flag_prompt
    prompt: "Digite uma letra:"
    default: "a"

  tasks:
  - name: "Se flag == 1 e flag_prompt == a "
    debug:
      msg: "{{ flag }}  {{ flag_prompt }}"
    when: 
    - flag == 1
    - flag_prompt == "b"
     


  - name: "Se flag == 1 ou flag_prompt == b "
    debug:
      msg: "{{ flag }}  {{ flag_prompt }}"
    when: >
        ( flag == 1  ) or
        ( flag_prompt == "a" ) 