---

- name: "play_01"
  hosts: Node_03
  tasks:
  - name: "Executa o comando df-h"
    shell: "df -h"
    register: variavel_registra_saida_do_comando

  - name: "Imprime o resultado"
    debug:
      msg: 
        - "=================================="
        - " {{ ansible_node_name }}"
        - "=================================="
        - "{{ variavel_registra_saida_do_comando.stdout_lines }}"  
      

- name: "play_01"
  hosts: Node_04
  tasks:
  - name: "Comando espaco em disco"
    shell: "df -h"
    register: variavel_registra_saida_do_comando

  - name: "Comando inode"
    shell: "df -i"
    register: 
  - name: "Imprime espaco em disco"
    debug:
      msg:
      - "============================="
      - " {{ ansible_node_name }}"
      - "============================="  
      - "{{ variavel_registra_saida_do_comando.stdout_lines }}"
      - "{{ variavel_registra_saida_do_comando.stdout_lines  }}"