---

- name: "play_01"
  hosts: front_end firewall
  tasks:
  - name: "Executa o comando df-h"
    shell: "df -h"
    register: variavel_registra_saida_do_comando

  - name: "Imprime o resultado"
    debug:
      msg: 
        - "=================================="
        - "{{ group_names }} - {{ ansible_node_name }}"
        - "=================================="
        - "{{ variavel_registra_saida_do_comando.stdout_lines }}"  
      

