---
- name: "Escrever e copiar"
  hosts: front_end
  tasks:
  - name: "Escrever e copiar"
    copy:
      content: |
        #!/bin/sh
        clear
        rm -f /tmp/*
        date
        ls -la /tmp/
      dest: "/tmp/test.sh"
      owner: user1
      group: user1
      mode: "770"
      
  - name: "Executa o script"
    shell:
       sh /tmp/test.sh
    register:  out

  - name: "Print"
    debug: 
      msg: "{{ out }}"  