---
- name: "Escrever e copiar"
  hosts: front_end
  tasks:
  - name: "Escrever e copiar"
    copy:
      content: |
<<<<<<< HEAD
        #!/bin/sh
=======
        #!/bin/bash
>>>>>>> 4c60a375bdbf476ecc58173eb67acfaa17bd852d
        clear
        rm -f /tmp/*
        date
        ls -la /tmp/
      dest: "/tmp/test.sh"
      owner: user1
      group: user1
      mode: "770"
      
<<<<<<< HEAD
  - name: "Executa o script"
    shell:
       sh /tmp/test.sh
    register:  out

  - name: "Print"
    debug: 
      msg: "{{ out }}"  
=======

    
>>>>>>> 4c60a375bdbf476ecc58173eb67acfaa17bd852d
